# Generated by Django 4.2.1 on 2023-05-21 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('-modified_at',)},
        ),
        migrations.AddField(
            model_name='chatmsg',
            name='message_sent',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 21, 9, 19, 34, 743455, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
