# Generated by Django 4.2.1 on 2023-05-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_options_chatmsg_message_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmsg',
            name='message_sent',
        ),
    ]
