# Generated by Django 4.2.1 on 2023-05-21 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chatmsg_message_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmsg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
